"""empty message

Revision ID: 136da131de5
Revises: 7a2a37be64
Create Date: 2015-11-23 20:59:45.508272

"""

# revision identifiers, used by Alembic.
revision = '136da131de5'
down_revision = '7a2a37be64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('state', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestone', 'state')
    ### end Alembic commands ###
