"""empty message

Revision ID: 162e9eaa38a
Revises: 3a6bf731def
Create Date: 2015-11-10 15:50:50.897100

"""

# revision identifiers, used by Alembic.
revision = '162e9eaa38a'
down_revision = '3a6bf731def'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('github', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'github')
    ### end Alembic commands ###
