"""empty message

Revision ID: 16644c80606
Revises: 405bf787587
Create Date: 2015-10-21 16:49:25.688768

"""

# revision identifiers, used by Alembic.
revision = '16644c80606'
down_revision = '405bf787587'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('duty_station', sa.String(), nullable=True))
    op.create_foreign_key(None, 'author', 'duty_station', ['duty_station'], ['airport_code'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.drop_column('author', 'duty_station')
    ### end Alembic commands ###
