"""empty message

Revision ID: 332bfcda4af
Revises: 136da131de5
Create Date: 2015-11-24 15:25:08.216410

"""

# revision identifiers, used by Alembic.
revision = '332bfcda4af'
down_revision = '136da131de5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.add_column('issue', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_constraint('issue_author_id_fkey', 'issue', type_='foreignkey')
    op.create_foreign_key(None, 'issue', 'author', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'issue', 'author', ['assignee_id'], ['id'])
    op.drop_column('issue', 'author_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'issue', type_='foreignkey')
    op.drop_constraint(None, 'issue', type_='foreignkey')
    op.create_foreign_key('issue_author_id_fkey', 'issue', 'author', ['author_id'], ['id'])
    op.drop_column('issue', 'creator_id')
    op.drop_column('issue', 'assignee_id')
    ### end Alembic commands ###
