"""empty message

Revision ID: 3a6bf731def
Revises: 4ae15f91f93
Create Date: 2015-11-09 20:56:41.051651

"""

# revision identifiers, used by Alembic.
revision = '3a6bf731def'
down_revision = '4ae15f91f93'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'issue', 'author', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issue', type_='foreignkey')
    op.drop_column('issue', 'author_id')
    ### end Alembic commands ###
