"""empty message

Revision ID: 405bf787587
Revises: 45e93babe0a
Create Date: 2015-10-21 16:29:25.683913

"""

# revision identifiers, used by Alembic.
revision = '405bf787587'
down_revision = '45e93babe0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('pronouns', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'pronouns')
    ### end Alembic commands ###
