"""empty message

Revision ID: 45e93babe0a
Revises: 3291788d2a4f
Create Date: 2015-10-20 21:23:32.837537

"""

# revision identifiers, used by Alembic.
revision = '45e93babe0a'
down_revision = '3291788d2a4f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duty_station',
    sa.Column('airport_code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('airport_code')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('duty_station')
    ### end Alembic commands ###
