"""empty message

Revision ID: 4ae15f91f93
Revises: 40e6626910b
Create Date: 2015-10-26 09:56:39.673334

"""

# revision identifiers, used by Alembic.
revision = '4ae15f91f93'
down_revision = '40e6626910b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('airport_code', sa.String(), nullable=True))
    op.add_column('author', sa.Column('team_id', sa.Integer(), nullable=True))
    op.drop_constraint('author_duty_station_fkey', 'author', type_='foreignkey')
    op.drop_constraint('author_team_fkey', 'author', type_='foreignkey')
    op.create_foreign_key(None, 'author', 'duty_station', ['airport_code'], ['airport_code'])
    op.create_foreign_key(None, 'author', 'team', ['team_id'], ['id'])
    op.drop_column('author', 'duty_station')
    op.drop_column('author', 'team')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('team', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('author', sa.Column('duty_station', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.create_foreign_key('author_team_fkey', 'author', 'team', ['team'], ['id'])
    op.create_foreign_key('author_duty_station_fkey', 'author', 'duty_station', ['duty_station'], ['airport_code'])
    op.drop_column('author', 'team_id')
    op.drop_column('author', 'airport_code')
    ### end Alembic commands ###
